CREATE SEQUENCE ORDER_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE ORDER_DETAIL_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE PAYMENT_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

-- 1. Create the main ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER DEFAULT ORDER_ID_SEQ.NEXTVAL PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL,
    SHIPPING_ADDRESS VARCHAR2(4000) NOT NULL,
    ORDER_STATUS VARCHAR2(20) DEFAULT 'Pending',
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create the ORDER_DETAILS table
CREATE TABLE ORDER_DETAILS (
    DETAIL_ID NUMBER DEFAULT ORDER_DETAIL_ID_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE_AT_PURCHASE NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE
);

-- 3.PAYMENTS table
CREATE TABLE payments (
    PAYMENT_ID NUMBER DEFAULT PAYMENT_ID_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PAYMENT_METHOD VARCHAR2(50),
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAY_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

