CREATE SEQUENCE USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE BOOK_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE TAG_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE USER_TABLE (
    USER_ID NUMBER DEFAULT USER_ID_SEQ.NEXTVAL PRIMARY KEY,
    USER_NAME VARCHAR2(100) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR2(100) CHECK (LENGTH(USER_PASSWORD) >= 8),
    USER_CREATION_DATE DATE DEFAULT (SYSDATE),
    USER_IS_ADMIN NUMBER(1) DEFAULT 0 CHECK (USER_IS_ADMIN = 0 OR USER_IS_ADMIN = 1)
);

CREATE TABLE BOOK (
    BOOK_ID NUMBER DEFAULT BOOK_ID_SEQ.NEXTVAL PRIMARY KEY,
    BOOK_TITLE VARCHAR2(100) UNIQUE NOT NULL,
    BOOK_DESCRIPTION VARCHAR2(1000),
    BOOK_CREATION_DATE DATE DEFAULT (SYSDATE)
);

CREATE TABLE TAG_TABLE (
    TAG_ID NUMBER DEFAULT TAG_ID_SEQ.NEXTVAL PRIMARY KEY,
    TAG_NAME VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE BOOK_TAG (
    BOOK_ID NUMBER REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    TAG_ID NUMBER REFERENCES TAG_TABLE(TAG_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW (
    USER_ID NUMBER REFERENCES USER_TABLE(USER_ID) ON DELETE CASCADE,
    BOOK_ID NUMBER REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
    REVIEW_TITLE VARCHAR2(100),
    REVIEW_RATING NUMBER(1) CHECK (REVIEW_RATING >= 0 AND REVIEW_RATING <= 5),
    REVIEW_DESCRIPTION VARCHAR2(1000),
    REVIEW_CREATION_DATE DATE DEFAULT (SYSDATE)
);