CREATE SEQUENCE USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE BOOK_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE TAG_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE ORDER_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE ORDER_DETAIL_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE PAYMENT_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE CUSTOMER_SERVICE_ID_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE MESSAGE_ID_SEQ
    START WITH 1
    INCREMENT BY 1;


CREATE TABLE USER_TB (
    USER_ID NUMBER DEFAULT USER_ID_SEQ.NEXTVAL PRIMARY KEY,
    USER_NAME VARCHAR2(100) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR2(100) CHECK (LENGTH(USER_PASSWORD) >= 8),
    USER_CREATION_DATE DATE DEFAULT (SYSDATE),
    USER_IS_ADMIN NUMBER(1) DEFAULT 0 CHECK (USER_IS_ADMIN = 0 OR USER_IS_ADMIN = 1)
);

CREATE TABLE MESSAGE_TB (
    MESSAGE_ID NUMBER DEFAULT MESSAGE_ID_SEQ.NEXTVAL PRIMARY KEY,
    MESSAGE VARCHAR2(1000) NOT NULL,
    SENDER VARCHAR2(100) NOT NULL
);

CREATE TABLE BOOK_TB (
    BOOK_ID NUMBER DEFAULT BOOK_ID_SEQ.NEXTVAL PRIMARY KEY,
    BOOK_TITLE VARCHAR2(100) UNIQUE NOT NULL,
    BOOK_AUTHOR VARCHAR2(100),
    BOOK_CATEGORY VARCHAR2(50),
    BOOK_DESCRIPTION VARCHAR2(1000),
    BOOK_PRICE NUMBER(10, 2) DEFAULT 0.00 CHECK (BOOK_PRICE >= 0),
    BOOK_QUANTITY NUMBER DEFAULT 0 CHECK (BOOK_QUANTITY >= 0),
    BOOK_IMAGE_PATH VARCHAR2(255),
    BOOK_CREATION_DATE DATE DEFAULT (SYSDATE)
);

CREATE TABLE TAG_TB (
    TAG_ID NUMBER DEFAULT TAG_ID_SEQ.NEXTVAL PRIMARY KEY,
    TAG_NAME VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE BOOK_TAG_TB (
    BOOK_ID NUMBER REFERENCES BOOK_TB(BOOK_ID) ON DELETE CASCADE,
    TAG_ID NUMBER REFERENCES TAG_TB(TAG_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW_TB (
    USER_ID NUMBER REFERENCES USER_TB(USER_ID) ON DELETE CASCADE,
    BOOK_ID NUMBER REFERENCES BOOK_TB(BOOK_ID) ON DELETE CASCADE,
    REVIEW_TITLE VARCHAR2(100),
    REVIEW_RATING NUMBER(1) CHECK (REVIEW_RATING >= 0 AND REVIEW_RATING <= 5),
    REVIEW_DESCRIPTION VARCHAR2(1000),
    REVIEW_CREATION_DATE DATE DEFAULT (SYSDATE)
);

CREATE TABLE ORDER_TB (
    ORDER_ID NUMBER DEFAULT ORDER_ID_SEQ.NEXTVAL PRIMARY KEY,
    USER_ID NUMBER REFERENCES USER_TB (USER_ID) ON DELETE CASCADE,
    TOTAL_AMOUNT NUMBER(10, 2) CHECK (TOTAL_AMOUNT >= 0),
    SHIPPING_ADDRESS VARCHAR2(4000) NOT NULL,
    ORDER_STATUS VARCHAR2(20) DEFAULT 'Pending',
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_DETAILS_TB (
    DETAIL_ID NUMBER DEFAULT ORDER_DETAIL_ID_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER REFERENCES ORDER_TB (ORDER_ID) ON DELETE CASCADE,
    BOOK_ID NUMBER REFERENCES BOOK_TB (BOOK_ID) ON DELETE CASCADE,
    QUANTITY NUMBER CHECK (QUANTITY >= 0),
    PRICE_AT_PURCHASE NUMBER(10, 2) CHECK (PRICE_AT_PURCHASE >= 0)
);

CREATE TABLE PAYMENT_TB (
    PAYMENT_ID NUMBER DEFAULT PAYMENT_ID_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER REFERENCES ORDER_TB (ORDER_ID) ON DELETE CASCADE,
    PAYMENT_METHOD VARCHAR2(50),
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
